### PR TITLE
Gus/health checks

### PR DESCRIPTION
**Pull request by GusTheGray**
Health checks at a basic level. I'll want to refactor later, but it's fine to merge as is (if amazon supports)
This addresses issue #134.

### CODE REVIEW

**Comment by GusTheGray** [comment]
@BillChirico looks like the travis instance needs to be updated with the new sdk.

**Comment by GusTheGray** [comment]
@BillChirico All packages are updated in this PR now.

**Comment by GusTheGray** [comment]
@BillChirico are we still waiting on support?

**Comment by BillChirico** [comment]
@GusTheGray Yeah, I created an issue https://travis-ci.community/t/net-core-2-2-support/1476

**Pull request merged**
